### ISSUE TITLE
/usr/bin/ld: CMakeFiles/clevo-fan-control.dir/src/main.c.o: undefined reference to symbol 'round@@GLIBC_2.2.5'

### ISSUE THREAD

**Issue by warrenc5** [agramian/clevo-fan-control#4]
please assist - I'm a little familiar with make.

clevo-fan-control on  main via △ 
❯ cmake --build .
[ 50%] Linking C executable clevo-fan-control
/usr/bin/ld: CMakeFiles/clevo-fan-control.dir/src/main.c.o: undefined reference to symbol 'round@@GLIBC_2.2.5'
/usr/bin/ld: /lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/clevo-fan-control.dir/build.make:97: clevo-fan-control] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/clevo-fan-control.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2

ii  libc6:amd64    2.35-0ubuntu3.4 amd64        GNU C Library: Shared libraries

**Comment by agramian** [comment]
Closing this as I believe this is no longer an issue now that #6 has been merged.
