### ISSUE TITLE
ec_sys module and linux debug kernels.

### ISSUE THREAD

**Issue by warrenc5** [agramian/clevo-fan-control#5]
Thanks this util works great on my mint clevo P960RD 
but not on my PD70PNP-1 running debian because it doesn't have the ec-sys module.

After reading https://bugzilla.redhat.com/show_bug.cgi?id=1943318

I am installing linux-image-6.5.0-5-amd64-dbg and switching to the debug kernel to try to get this running.

Hope this helps others in the same/similar predicament

I humbly ask the author to consider writing a proper dkms based kernel module for the clevo.

**Comment by agramian** [comment]
Hi, you can try installing https://github.com/musikid/acpi_ec for distributions that are missing the ec_sys module.

I no longer own a Clevo laptop so I don't have plans to continue development on this project at the moment but will gladly review pull requests. I'm using another project which also requires ec_sys for fan control on my MSI laptop and using the above mentioned project is working properly with kernel version 6.4.12 so hopefully it will work for you as well with this project.

**Comment by warrenc5** [comment]
I see that the modules' device node path is only used for reading. And that ec writing is done using low level io - outb calls.

pull request is here -> https://github.com/agramian/clevo-fan-control/pull/6

**Comment by agramian** [comment]
Closing this as I believe this is no longer an issue now that #6 has been merged.
